const ADD_CAMERA = 'ADD_CAMERA';
const REMOVE_CAMERA = 'REMOVE_CAMERA';
const SELECT_CAMERA = 'SELECT_CAMERA';
const CLEAR_CAMERAS = 'CLEAR_CAMERAS';
const UPDATE_CAMERA_LOCATION = 'UPDATE_CAMERA_LOCATION';

const ADD_CAMERA_TYPE = 'ADD_CAMERA_TYPE';
const REMOVE_CAMERA_TYPE = 'REMOVE_CAMERA_TYPE';
const SELECT_CAMERA_TYPE = 'SELECT_CAMERA_TYPE';
const CLEAR_CAMERA_TYPES = 'CLEAR_CAMERA_TYPES';

const CHANGE_MAP_ZOOM = 'CHANGE_MAP_ZOOM';

const UPDATE_SETTINGS = 'UPDATE_SETTINGS';

const REPLACE_STATE = 'REPLACE_STATE';

module.exports = {
  ADD_CAMERA,
  REMOVE_CAMERA,
  CLEAR_CAMERAS,
  SELECT_CAMERA,

  ADD_CAMERA_TYPE,
  REMOVE_CAMERA_TYPE,
  SELECT_CAMERA_TYPE,
  CLEAR_CAMERA_TYPES,

  UPDATE_CAMERA_LOCATION,
  CHANGE_MAP_ZOOM,

  UPDATE_SETTINGS,

  REPLACE_STATE
};