#!/bin/bash

set -e

rm -rf dist/*
env NODE_ENV=production webpack -P --json > /tmp/bundle.json
echo 'Build done !'

BUNDLE_NAME=$(cd dist && ls bundle*)

cp src/shared/index.html dist/
cp src/shared/favicon.ico dist/
sed -i '' "s/__BUNDLE_NAME__/${BUNDLE_NAME}/" dist/index.html
